# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180615_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='branch',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
